import{randomBytes,randomUUID}from"node:crypto";import type{WebSocket}from"ws";import{JOIN_WINDOW_MS,SESSION_LIFETIME_MS,type ServerMessage}from"./protocol.js";
const ALPHABET="23456789ABCDEFGHJKLMNPQRSTUVWXYZ";export type PeerRole="host"|"helper";
export interface Room{code:string;host:WebSocket;helper?:WebSocket;requestId?:string;createdAt:number;joinExpiresAt:number;sessionExpiresAt:number;accepted:boolean;timer:NodeJS.Timeout;}
export class RoomRegistry{readonly rooms=new Map<string,Room>();readonly peers=new WeakMap<WebSocket,{room:Room;role:PeerRole}>();constructor(private readonly now=()=>Date.now()){}
create(host:WebSocket):Room{this.removePeer(host,"replaced");let code="";do{code=generateCode();}while(this.rooms.has(code));const createdAt=this.now();const room:Room={code,host,createdAt,joinExpiresAt:createdAt+JOIN_WINDOW_MS,sessionExpiresAt:createdAt+SESSION_LIFETIME_MS,accepted:false,timer:setTimeout(()=>this.end(room,"expired"),SESSION_LIFETIME_MS)};room.timer.unref();this.rooms.set(code,room);this.peers.set(host,{room,role:"host"});this.send(host,{type:"room-created",code:formatCode(code),expiresAt:room.joinExpiresAt});return room;}
join(helper:WebSocket,code:string,helperName:string):boolean{const room=this.rooms.get(code);if(!room||room.accepted||room.helper||this.now()>=room.joinExpiresAt){this.send(helper,{type:"error",code:"room_unavailable"});return false;}room.helper=helper;room.requestId=randomUUID();this.peers.set(helper,{room,role:"helper"});this.send(helper,{type:"waiting"});this.send(room.host,{type:"join-request",requestId:room.requestId,helperName});return true;}
respond(host:WebSocket,requestId:string,accept:boolean):void{const peer=this.peers.get(host),room=peer?.room;if(!room||peer?.role!=="host"||room.requestId!==requestId||!room.helper){this.send(host,{type:"error",code:"invalid_request"});return;}if(!accept){this.send(room.helper,{type:"declined"});this.peers.delete(room.helper);room.helper.close(4003,"declined");room.helper=undefined;room.requestId=undefined;return;}room.accepted=true;this.send(room.helper,{type:"accepted",expiresAt:room.sessionExpiresAt});this.send(host,{type:"accepted",expiresAt:room.sessionExpiresAt});}
relay(sender:WebSocket,message:ServerMessage&{type:"signal"}):void{const peer=this.peers.get(sender);if(!peer?.room.accepted){this.send(sender,{type:"error",code:"not_accepted"});return;}const target=peer.role==="host"?peer.room.helper:peer.room.host;if(target&&target.readyState===target.OPEN)this.send(target,message);}
removePeer(socket:WebSocket,reason="peer_disconnected"):void{const peer=this.peers.get(socket);if(!peer)return;const room=peer.room;this.peers.delete(socket);if(peer.role==="host")this.end(room,reason);else{room.helper=undefined;room.requestId=undefined;if(room.accepted)this.end(room,reason);}}
end(room:Room,reason:string):void{if(!this.rooms.delete(room.code))return;clearTimeout(room.timer);this.peers.delete(room.host);if(room.helper)this.peers.delete(room.helper);this.send(room.host,{type:"ended",reason});if(room.helper)this.send(room.helper,{type:"ended",reason});room.host.close(1000,reason);room.helper?.close(1000,reason);}
private send(socket:WebSocket,message:ServerMessage):void{if(socket.readyState===socket.OPEN)socket.send(JSON.stringify(message));}}
export function generateCode():string{const bytes=randomBytes(12);let result="";for(let i=0;i<12;i++)result+=ALPHABET[bytes[i]!%ALPHABET.length];return result;}export function formatCode(code:string):string{return`${code.slice(0,4)}-${code.slice(4,8)}-${code.slice(8,12)}`;}
