package family.remote.protocol
import okhttp3.*
import org.json.JSONObject
import java.util.concurrent.TimeUnit
class RendezvousClient(private val listener:Listener,private val url:String=DEFAULT_URL):WebSocketListener(),AutoCloseable{private val http=OkHttpClient.Builder().pingInterval(30,TimeUnit.SECONDS).build();private var socket:WebSocket?=null;@Volatile var signalListener:((String,String)->Unit)?=null
fun connect(){socket=http.newWebSocket(Request.Builder().url(url).build(),this)};fun createRoom()=send(JSONObject().put("type","create"));fun join(code:String,name:String)=send(JSONObject().put("type","join").put("code",code).put("helperName",name.take(60)));fun respond(id:String,accept:Boolean)=send(JSONObject().put("type","respond").put("requestId",id).put("accept",accept));fun signal(kind:String,payload:String){if(payload.length<=32*1024)send(JSONObject().put("type","signal").put("kind",kind).put("payload",payload))}
override fun onOpen(ws:WebSocket,response:Response)=listener.onOpen();override fun onMessage(ws:WebSocket,text:String){runCatching{JSONObject(text)}.getOrNull()?.let(::dispatch)};override fun onFailure(ws:WebSocket,t:Throwable,response:Response?)=listener.onError("service_unavailable");override fun onClosed(ws:WebSocket,code:Int,reason:String)=listener.onEnded(if(reason.isBlank())"disconnected" else reason)
private fun dispatch(v:JSONObject){when(v.optString("type")){"room-created"->listener.onRoomCreated(v.getString("code"),v.getLong("expiresAt"));"join-request"->listener.onJoinRequest(v.getString("requestId"),v.optString("helperName","Family helper"));"waiting"->listener.onWaiting();"accepted"->listener.onAccepted(v.getLong("expiresAt"));"declined"->listener.onDeclined();"signal"->signalListener?.invoke(v.getString("kind"),v.getString("payload"));"ended"->listener.onEnded(v.optString("reason","ended"));"error"->listener.onError(v.optString("code","unknown"))}};private fun send(v:JSONObject){socket?.send(v.toString())};override fun close(){socket?.send("{\"type\":\"leave\"}");socket?.close(1000,"peer_left");socket=null}
interface Listener{fun onOpen(){};fun onRoomCreated(code:String,expiresAt:Long){};fun onJoinRequest(requestId:String,helperName:String){};fun onWaiting(){};fun onAccepted(expiresAt:Long){};fun onDeclined(){};fun onEnded(reason:String){};fun onError(code:String){}}
companion object{const val DEFAULT_URL="wss://kinpilot-rendezvous.onrender.com/ws"}}
